// Lookup for TFT display names and icons, backed by public/tft/manifest.json
// (generated by scripts/fetch-assets.mjs). The manifest is fetched once and
// shared; if it's missing (assets never downloaded) every lookup falls back
// to a name derived from the Riot id, so pages still render as text.

import { useEffect, useState } from "react";

export type AssetKind = "champions" | "traits" | "augments" | "items";

interface AssetEntry {
  name: string;
  icon?: string;
  cost?: number;
}

export interface Manifest {
  version: string;
  champions: Record<string, AssetEntry>;
  traits: Record<string, AssetEntry>;
  augments: Record<string, AssetEntry>;
  items: Record<string, AssetEntry>;
}

let manifestPromise: Promise<Manifest | null> | null = null;
let manifestCache: Manifest | null = null;

function loadManifest(): Promise<Manifest | null> {
  manifestPromise ??= fetch("/tft/manifest.json")
    .then((r) => (r.ok ? (r.json() as Promise<Manifest>) : null))
    .catch(() => null)
    .then((m) => (manifestCache = m));
  return manifestPromise;
}

export function useManifest(): Manifest | null {
  const [manifest, setManifest] = useState(manifestCache);
  useEffect(() => {
    if (!manifest) loadManifest().then(setManifest);
  }, [manifest]);
  return manifest;
}

export function formatId(id: string): string {
  const idx = id.indexOf("_");
  return idx >= 0 ? id.slice(idx + 1) : id;
}

// Riot occasionally emits ids with different casing (e.g. "tft15_leesin").
const lowercaseIndex = new WeakMap<Record<string, AssetEntry>, Map<string, AssetEntry>>();

function findInsensitive(entries: Record<string, AssetEntry>, id: string): AssetEntry | undefined {
  let index = lowercaseIndex.get(entries);
  if (!index) {
    index = new Map(Object.entries(entries).map(([k, v]) => [k.toLowerCase(), v]));
    lowercaseIndex.set(entries, index);
  }
  return index.get(id.toLowerCase());
}

export function lookup(manifest: Manifest | null, kind: AssetKind, id: string): AssetEntry {
  const entries = manifest?.[kind];
  return (entries && (entries[id] ?? findInsensitive(entries, id))) ?? { name: formatId(id) };
}

export function profileIconUrl(manifest: Manifest | null, iconId: number): string | null {
  // Profile icons are shared with League (thousands of them), so they're
  // loaded from the CDN on demand rather than downloaded.
  return manifest ? `https://ddragon.leagueoflegends.com/cdn/${manifest.version}/img/profileicon/${iconId}.png` : null;
}

interface GameIconProps {
  kind: AssetKind;
  id: string;
  size?: number;
  className?: string;
}

/** Square icon for a champion/trait/augment/item, with the display name as a tooltip. */
export function GameIcon({ kind, id, size = 32, className = "" }: GameIconProps) {
  const manifest = useManifest();
  const entry = lookup(manifest, kind, id);
  const [broken, setBroken] = useState(false);
  const cost = kind === "champions" ? entry.cost : undefined;
  const classes = `game-icon game-icon-${kind} ${cost ? `cost-${cost}` : ""} ${className}`;

  if (!entry.icon || broken) {
    return (
      <span className={`${classes} game-icon-missing`} style={{ width: size, height: size }} title={entry.name}>
        {entry.name.slice(0, 2)}
      </span>
    );
  }
  return (
    <img
      className={classes}
      src={entry.icon}
      alt={entry.name}
      title={entry.name}
      width={size}
      height={size}
      loading="lazy"
      onError={() => setBroken(true)}
    />
  );
}

/** Icon followed by display name, for table cells. */
export function GameLabel({ kind, id, size = 28 }: Omit<GameIconProps, "className">) {
  const manifest = useManifest();
  return (
    <span className="game-label">
      <GameIcon kind={kind} id={id} size={size} />
      {lookup(manifest, kind, id).name}
    </span>
  );
}
